name: claudiadecarlo.com
author: Claudia De Carlo
url: https://claudiadecarlo.com/
email: hello@claudiadecarlo.com
showSubscribeForm: true
subscribeHeading: Mantente al tanto de las novedades
subscribeSummary: >-
  Si te interesa el crecimiento personal, cambiar tu mentalidad y crear una vida
  que realmente sientas como tuya, estás en el lugar correcto.


  Déjame tu email abajo y recibirás:


  Solo compartiré contigo contenido que te aporte valor, te inspire y te ayude en tu camino.
subscribeLabel: Tu dirección de correo electrónico
subscribeButton: Suscribirme
contactFormHeading: ¿Tienes alguna pregunta o te sientes llamado a conectarte?
contactFormSummary: Si tienes curiosidad por colaborar, quieres explorar una
  idea o simplemente necesitas aclarar algo que has visto aquí, me encantaría
  saber de ti. Completa el formulario a continuación y me pondré en contacto
  contigo pronto.
contactFormFirstNameLabel: Nombre
contactFormLastNameLabel: Apellido
contactFormEmailLabel: Correo electrónico
contactFormTelephoneLabel: Número de teléfono
contactFormMessageLabel: ¿Cómo crees que podría ayudarte?
contactFormMessageHelper: No necesitas entrar en muchos detalles aquí, una breve descripción está bien.
contactFormButton: Enviar
languageSwitcherLabel: Seleccionar idioma
footerText: Todos los derechos reservados
