name: claudiadecarlo.com
author: Claudia De Carlo
url: https://claudiadecarlo.com/
email: hello@claudiadecarlo.com
showSubscribeForm: true
subscribeHeading: Mantente en contacto
subscribeSummary: >-
  Si te interesa el crecimiento personal, los cambios de mentalidad y crear una
  vida que realmente sientas como tuya, estás en el lugar correcto.


  Regístrate a continuación para recibir:


  * Actualizaciones y reflexiones inspiradoras

  * Recursos gratuitos para apoyar tu viaje

  * Ofertas exclusivas y acceso anticipado a mis talleres, cursos y eventos.


  Solo te enviaré lo que te convenga, te sea útil y te agrade. Crezcamos juntos.
subscribeLabel: Tu dirección de correo electrónico
subscribeButton: Suscribirse
contactFormHeading: ¿Tienes alguna pregunta o te sientes llamado a conectarte?
contactFormSummary: Si tienes curiosidad por colaborar, quieres explorar una
  idea o simplemente necesitas aclarar algo que has visto aquí, me encantaría
  saber de ti. Completa el formulario a continuación y me pondré en contacto
  contigo pronto.
contactFormButton: Entregar
languageSwitcherLabel: Seleccionar idioma
footerText: Todos los derechos reservados
