name: claudiadecarlo.com
author: Claudia De Carlo
url: https://claudiadecarlo.com/
email: hello@claudiadecarlo.com
showSubscribeForm: true
subscribeHeading: Stay in Touch
subscribeSummary: >-
  If you’re into personal growth, mindset shifts, and creating a life that truly
  feels like yours - you’re in the right place.


  Sign up below to receive:


  * Inspiring updates and reflections

  * Free resources to support your journey

  * Exclusive offers and early access to my workshops, courses, and events




  I’ll only send what’s aligned, useful, and worth your time. Let’s grow together.
subscribeButton: Subscribe
contactFormHeading: Have a question or feel called to connect?
contactFormSummary: Whether you're curious about working together, want to
  explore an idea, or simply need clarity on something you’ve seen here, I’d
  love to hear from you. Fill in the form below and I’ll be in touch soon.
contactFormButton: Submit
