backend:
    name: git-gateway
    repo: jimbateson7/https-claudiadecarlo.com-
    branch: feat/translations
    identity_url: https://auth.decapbridge.com/sites/dbf9a222-86ae-41b0-b126-7fa01c460399
    gateway_url: https://gateway.decapbridge.com

publish_mode: editorial_workflow
media_folder: 'src/static/uploads'
public_folder: '/static/uploads'
logo_url: https://decapbridge.com/decapcms-with-bridge.svg
site_url: https://claudiadecarlo.com

local_backend: true

collections:
    # Pages - English
    - name: 'pages_en'
      label: 'Pages (English)'
      files:
          - name: 'home_en'
            label: 'Homepage'
            delete: false
            file: 'src/en/index.html'
            slug: '{{slug}}'
            create: false
            fields:
                - { label: 'Title', name: 'title', widget: 'string' }
                - { label: 'Body', name: 'body', widget: 'markdown' }

          - name: 'myApproach_en'
            label: 'My Approach'
            delete: false
            file: 'src/en/my-approach.html'
            slug: '{{slug}}'
            create: false
            fields:
                - { label: 'Title', name: 'title', widget: 'string' }
                - { label: 'Body', name: 'body', widget: 'markdown' }

    # Pages - Spanish
    - name: 'pages_es'
      label: 'Pages (Spanish)'
      files:
          - name: 'home_es'
            label: 'Homepage'
            delete: false
            file: 'src/es/index.html'
            slug: '{{slug}}'
            create: false
            fields:
                - { label: 'Title', name: 'title', widget: 'string' }
                - { label: 'Body', name: 'body', widget: 'markdown' }

          - name: 'myApproach_es'
            label: 'My Approach'
            delete: false
            file: 'src/es/my-approach.html'
            slug: '{{slug}}'
            create: false
            fields:
                - { label: 'Title', name: 'title', widget: 'string' }
                - { label: 'Body', name: 'body', widget: 'markdown' }

    # Static Pages - English
    - name: 'static_pages_en'
      label: 'Static Pages (English)'
      folder: 'src/en/pages'
      slug: '{{slug}}'
      preview_path: 'pages/{{slug}}'
      create: true
      fields:
          - { label: 'Title', name: 'title', widget: 'string' }
          - { label: 'Body', name: 'body', widget: 'markdown' }

    # Static Pages - Spanish
    - name: 'static_pages_es'
      label: 'Static Pages (Spanish)'
      folder: 'src/es/pages'
      slug: '{{slug}}'
      preview_path: 'pages/{{slug}}'
      create: true
      fields:
          - { label: 'Title', name: 'title', widget: 'string' }
          - { label: 'Body', name: 'body', widget: 'markdown' }

    # Blog - English
    - label: 'Blog (English)'
      name: 'blog_en'
      folder: 'src/en/posts'
      create: true
      editor:
          preview: false
      fields:
          - { label: 'Title', name: 'title', widget: 'string' }
          - { label: 'Publish Date', name: 'date', widget: 'datetime' }
          - { label: 'Body', name: 'body', widget: 'markdown' }

    # Blog - Spanish
    - label: 'Blog (Spanish)'
      name: 'blog_es'
      folder: 'src/es/posts'
      create: true
      editor:
          preview: false
      fields:
          - { label: 'Title', name: 'title', widget: 'string' }
          - { label: 'Publish Date', name: 'date', widget: 'datetime' }
          - { label: 'Body', name: 'body', widget: 'markdown' }

    # Services - English
    - label: 'Services (English)'
      name: 'services_en'
      folder: 'src/en/services'
      create: true
      fields:
          - { label: 'Title', name: 'title', widget: 'string' }
          - { label: 'Description', name: 'description', widget: 'markdown' }

    # Services - Spanish
    - label: 'Services (Spanish)'
      name: 'services_es'
      folder: 'src/es/services'
      create: true
      fields:
          - { label: 'Title', name: 'title', widget: 'string' }
          - { label: 'Description', name: 'description', widget: 'markdown' }

    # Testimonials - English
    - label: 'Testimonials (English)'
      name: 'testimonials_en'
      folder: 'src/en/testimonials'
      create: true
      slug: '{{fields.testimonialAuthor | slug}}'
      fields:
          - { label: 'Author', name: 'testimonialAuthor', widget: 'string' }
          - { label: 'Body', name: 'testimonialBody', widget: 'markdown' }

    # Testimonials - Spanish
    - label: 'Testimonials (Spanish)'
      name: 'testimonials_es'
      folder: 'src/es/testimonials'
      create: true
      slug: '{{fields.testimonialAuthor | slug}}'
      fields:
          - { label: 'Author', name: 'testimonialAuthor', widget: 'string' }
          - { label: 'Body', name: 'testimonialBody', widget: 'markdown' }

    # Global Data - English
    - label: 'Global (English)'
      name: 'global_en'
      editor:
          preview: false
      files:
          - label: 'Header Navigation'
            name: 'headerNavigation'
            file: 'src/_data/en/headerNavigation.yaml'
            fields:
                - label: Header Nav Items
                  name: headerItems
                  widget: list
                  allow_add: true
                  allow_delete: true
                  collapsed: false
                  fields:
                      - label: Title
                        name: text
                        widget: string
                      - label: URL
                        name: url
                        widget: string

          - label: 'Footer Navigation'
            name: 'footerNavigation'
            file: 'src/_data/en/footerNavigation.yaml'
            fields:
                - label: Footer Nav Items
                  name: footerItems
                  widget: list
                  allow_add: true
                  allow_delete: true
                  collapsed: false
                  fields:
                      - label: Title
                        name: text
                        widget: string
                      - label: URL
                        name: url
                        widget: string

          - label: 'Social Links'
            name: 'socialLinks'
            file: 'src/_data/en/socialLinks.yaml'
            fields:
                - label: Social Items
                  name: socialItems
                  widget: list
                  allow_add: true
                  allow_delete: true
                  collapsed: false
                  fields:
                      - label: Title
                        name: text
                        widget: string
                      - label: URL
                        name: url
                        widget: string

          - label: 'Site Settings'
            name: 'siteSettings'
            file: 'src/_data/en/siteSettings.yaml'
            fields:
                - label: Name
                  name: name
                  widget: string
                - label: Author
                  name: author
                  widget: string
                - label: URL
                  name: url
                  widget: string
                - label: Email Address
                  name: email
                  widget: string
                - label: Show Subscribe Form
                  name: showSubscribeForm
                  widget: boolean
                  default: true
                - label: Subscribe Heading
                  name: subscribeHeading
                  widget: string
                - label: Subscribe Summary
                  name: subscribeSummary
                  widget: markdown
                - label: Subscribe Button
                  name: subscribeButton
                  widget: string
                - label: 'Contact Form Heading'
                  name: contactFormHeading
                  widget: string
                - label: 'Contact Form Summary'
                  name: contactFormSummary
                  widget: markdown
                - label: 'Contact Form Button'
                  name: contactFormButton
                  widget: string

    # Global Data - Spanish
    - label: 'Global (Spanish)'
      name: 'global_es'
      editor:
          preview: false
      files:
          - label: 'Header Navigation'
            name: 'headerNavigation'
            file: 'src/_data/es/headerNavigation.yaml'
            fields:
                - label: Header Nav Items
                  name: headerItems
                  widget: list
                  allow_add: true
                  allow_delete: true
                  collapsed: false
                  fields:
                      - label: Title
                        name: text
                        widget: string
                      - label: URL
                        name: url
                        widget: string

          - label: 'Footer Navigation'
            name: 'footerNavigation'
            file: 'src/_data/es/footerNavigation.yaml'
            fields:
                - label: Footer Nav Items
                  name: footerItems
                  widget: list
                  allow_add: true
                  allow_delete: true
                  collapsed: false
                  fields:
                      - label: Title
                        name: text
                        widget: string
                      - label: URL
                        name: url
                        widget: string

          - label: 'Social Links'
            name: 'socialLinks'
            file: 'src/_data/es/socialLinks.yaml'
            fields:
                - label: Social Items
                  name: socialItems
                  widget: list
                  allow_add: true
                  allow_delete: true
                  collapsed: false
                  fields:
                      - label: Title
                        name: text
                        widget: string
                      - label: URL
                        name: url
                        widget: string

          - label: 'Site Settings'
            name: 'siteSettings'
            file: 'src/_data/es/siteSettings.yaml'
            fields:
                - label: Name
                  name: name
                  widget: string
                - label: Author
                  name: author
                  widget: string
                - label: URL
                  name: url
                  widget: string
                - label: Email Address
                  name: email
                  widget: string
                - label: Show Subscribe Form
                  name: showSubscribeForm
                  widget: boolean
                  default: true
                - label: Subscribe Heading
                  name: subscribeHeading
                  widget: string
                - label: Subscribe Summary
                  name: subscribeSummary
                  widget: markdown
                - label: Subscribe Button
                  name: subscribeButton
                  widget: string
                - label: 'Contact Form Heading'
                  name: contactFormHeading
                  widget: string
                - label: 'Contact Form Summary'
                  name: contactFormSummary
                  widget: markdown
                - label: 'Contact Form Button'
                  name: contactFormButton
                  widget: string
