backend:
    name: github
    repo: jimbateson7/https-claudiadecarlo.com-

publish_mode: editorial_workflow
media_folder: 'src/static/img'
public_folder: '/static/img'
site_url: https://claudiadecarlo.com/
display_url: https://claudiadecarlo.com
logo_url: https://claudiadecarlo.com/img/3F6J-6VwmB-261.webp

# Run "npx netlify-cms-proxy-server" for local backend
local_backend: true

collections:
    - name: 'pages'
      label: 'Pages'
      files:
          - name: 'home'
            label: 'Homepage'
            delete: false
            file: 'src/index.html'
            slug: '{{slug}}'
            create: false
            fields:
                - label: 'Layout'
                  name: 'layout'
                  widget: 'hidden'
                  default: 'layouts/njk.njk'

                - label: 'SEO Meta Title'
                  name: 'metaTitle'
                  widget: 'string'
                  required: false

                - label: 'SEO Meta Description'
                  name: 'metaDesc'
                  widget: 'string'
                  required: false

                - label: 'Social Image'
                  name: 'socialImage'
                  widget: 'image'
                  required: false

                - label: 'Avatar Image'
                  name: 'avatarImage'
                  widget: 'image'

                - label: 'Title'
                  name: 'title'
                  widget: 'string'

                - label: 'Subtitle'
                  name: 'subtitle'
                  widget: 'string'

                - label: 'Hero Image'
                  name: 'heroImage'
                  widget: 'image'

                - label: 'Collage Heading'
                  name: 'collageHeading'
                  widget: 'string'
                  required: false

                - label: 'Collage Summary'
                  name: 'collageSummary'
                  widget: 'markdown'
                  required: false

                - label: 'Collage Image'
                  name: 'collageImage'
                  widget: 'image'
                  required: false

                - label: 'How I help Title'
                  name: 'howIHelpTitle'
                  widget: 'string'

                - label: 'Services to Show'
                  name: 'servicesToShow'
                  widget: 'number'
                  default: 3
                  min: 3

                - label: 'Testimonials Title'
                  name: 'testimonialsTitle'
                  widget: 'string'

                - label: 'Testimonials to Show'
                  name: 'testimonialsToShow'
                  widget: 'number'
                  default: 3
                  min: 3

                - label: About Title
                  name: 'aboutTitle'
                  widget: 'string'

                - label: About Summary
                  name: 'aboutSummary'
                  widget: 'markdown'

                - label: About Image
                  name: 'aboutImage'
                  widget: 'image'

                - label: 'About Link Text'
                  name: 'aboutLinkText'
                  widget: 'string'

                - label: 'About Link URL'
                  name: 'aboutLinkUrl'
                  widget: 'string'

                - label: Contact Title
                  name: 'contactTitle'
                  widget: 'string'

                - label: Contact Summary
                  name: 'contactSummary'
                  widget: 'markdown'

                - label: Contact Image
                  name: 'contactImage'
                  widget: 'image'

                - label: 'Contact Link Text'
                  name: 'contactLinkText'
                  widget: 'string'

                - label: 'Contact Link URL'
                  name: 'contactLinkUrl'
                  widget: 'string'
    - name: 'static_pages'
      label: 'Static Pages'
      folder: 'src/pages'
      slug: '{{slug}}'
      preview_path: 'pages/{{slug}}'
      create: true
      fields:
          - {
                label: 'Layout',
                name: 'layout',
                widget: 'hidden',
                default: 'page.html',
            }

          - { label: 'Title', name: 'title', widget: 'string' }

          - {
                label: 'Banner Image',
                name: 'bannerImage',
                widget: 'image',
                required: false,
            }

          - {
                label: 'Permalink Override',
                name: 'permalink',
                widget: 'string',
                required: false,
            }

          - {
                label: 'SEO Meta Title',
                name: 'metaTitle',
                widget: 'string',
                required: false,
            }

          - {
                label: 'SEO Meta Description',
                name: 'metaDesc',
                widget: 'string',
                required: false,
            }

          - {
                label: 'Social Image',
                name: 'socialImage',
                widget: 'image',
                required: false,
            }

          - { label: 'Body', name: 'body', widget: 'markdown' }
    - label: 'Blog'
      name: 'blog'
      folder: 'src/posts'
      create: true
      editor:
          preview: false
      fields:
          - label: 'Title'
            name: 'title'
            widget: 'string'

          - label: 'Description'
            name: 'description'
            widget: 'string'
            required: false

          - label: 'Card Image'
            name: 'cardImage'
            widget: 'image'
            required: false

          - label: 'Banner Image'
            name: 'bannerImage'
            widget: 'image'
            required: false

          - label: 'Author'
            name: 'author'
            default: 'Claudia De Carlo'
            widget: 'string'

          - label: 'Author Image'
            name: 'authorImage'
            widget: 'image'
            required: false

          - label: 'Publish Date'
            name: 'date'
            widget: 'datetime'
            date_format: 'DD/MM/YYYY'

          - label: 'Body'
            name: 'body'
            widget: 'markdown'

          - label: 'Tags'
            name: 'tags'
            widget: 'list'
            required: false

    - label: 'Services'
      name: 'services'
      folder: 'src/services'
      create: true
      fields:
          - label: 'Layout'
            name: 'layout'
            widget: 'hidden'
            default: 'page.html'

          - label: 'Title'
            name: 'title'
            widget: 'string'

          - label: 'Card Image'
            name: 'cardImage'
            widget: 'image'

          - label: 'Summary'
            name: 'summary'
            widget: 'markdown'

          - label: 'Banner Image'
            name: 'bannerImage'
            widget: 'image'
            required: false

          - label: 'Body'
            name: 'body'
            widget: 'markdown'

    - label: 'Testimonials'
      name: 'testimonials'
      folder: 'src/testimonials'
      create: true
      slug: '{{fields.testimonialAuthor | slug}}'
      fields:
          - label: 'Layout'
            name: 'layout'
            widget: 'hidden'
            default: 'page.html'

          - label: 'Author'
            name: 'testimonialAuthor'
            widget: 'string'

          - label: 'Author Location'
            name: 'testimonialAuthorLocation'
            widget: 'string'
            required: false

          - label: 'Author Image'
            name: 'testimonialAuthorImage'
            widget: 'image'
            required: false

          - label: 'Quote'
            name: 'quote'
            widget: 'markdown'

          - label: 'Show Story?'
            name: 'showStory'
            widget: 'boolean'
            default: false

          - label: 'Body'
            name: 'body'
            widget: 'markdown'
            required: false

    - label: 'Global'
      name: 'global'
      description: 'General site settings that are used across multiple pages. Note that social links added will appear in the homepage banner and footer.'
      editor:
          preview: false
      files:
          - label: 'Header Navigation'
            name: 'headerNavigation'
            file: 'src/_data/headerNavigation.yaml'
            fields:
                - label: Header Nav Items
                  name: headerItems
                  widget: list
                  allow_add: true
                  allow_delete: true
                  collapsed: false
                  fields:
                      - label: Title
                        name: text
                        widget: string
                      - label: URL
                        name: url
                        widget: string

          - label: 'Footer Navigation'
            name: 'footerNavigation'
            file: 'src/_data/footerNavigation.yaml'
            fields:
                - label: Footer Nav Items
                  name: footerItems
                  widget: list
                  allow_add: true
                  allow_delete: true
                  collapsed: false
                  fields:
                      - label: Title
                        name: text
                        widget: string
                      - label: URL
                        name: url
                        widget: string

          - label: 'Social Links'
            name: 'socialLinks'
            file: 'src/_data/socialLinks.yaml'
            fields:
                - label: Social Items
                  name: socialItems
                  widget: list
                  allow_add: true
                  allow_delete: true
                  collapsed: false
                  fields:
                      - label: Title
                        name: text
                        widget: string
                      - label: URL
                        name: url
                        widget: string

          - label: 'Site Settings'
            name: 'siteSettings'
            file: 'src/_data/siteSettings.yaml'
            fields:
                - label: Name
                  name: name
                  widget: string
                - label: Author
                  name: author
                  widget: string
                - label: URL
                  name: url
                  widget: string
                - label: Email Address
                  name: email
                  widget: string
                - label: Show Subscribe Form
                  name: showSubscribeForm
                  widget: boolean
                  default: true
                - label: Subscribe Heading
                  name: subscribeHeading
                  widget: string
                - label: Subscribe Summary
                  name: subscribeSummary
                  widget: markdown
                - label: Subscribe Button
                  name: subscribeButton
                  widget: string
